const BAD_REQUEST_CODE = 400;
const NOT_AUTHORIZED_CODE = 401;
const STATUS_OK_CODE = 200;
const PLAYER_ALREADY_INITIATED_GAME = 'player-have-initiated-game';

export {
  BAD_REQUEST_CODE,
  NOT_AUTHORIZED_CODE,
  STATUS_OK_CODE,
  PLAYER_ALREADY_INITIATED_GAME
}
